# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '/mnt/hgfs/Developpement/Debian_Dev/Eclipse/Workspace/BoardSimu/src/Ui/boardSimuUi.ui'
#
# Created: Fri May 23 10:56:51 2014
#      by: PyQt4 UI code generator 4.9.3
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    _fromUtf8 = lambda s: s

class Ui_BoardSimuMain(object):
    def setupUi(self, BoardSimuMain):
        BoardSimuMain.setObjectName(_fromUtf8("BoardSimuMain"))
        BoardSimuMain.resize(546, 657)
        self.centralwidget = QtGui.QWidget(BoardSimuMain)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.centralwidget.sizePolicy().hasHeightForWidth())
        self.centralwidget.setSizePolicy(sizePolicy)
        self.centralwidget.setObjectName(_fromUtf8("centralwidget"))
        self.gridLayout_2 = QtGui.QGridLayout(self.centralwidget)
        self.gridLayout_2.setObjectName(_fromUtf8("gridLayout_2"))
        self.gridLayout = QtGui.QGridLayout()
        self.gridLayout.setObjectName(_fromUtf8("gridLayout"))
        self.verticalLayout = QtGui.QVBoxLayout()
        self.verticalLayout.setObjectName(_fromUtf8("verticalLayout"))
        self.programEdit = QtGui.QPlainTextEdit(self.centralwidget)
        self.programEdit.setLineWrapMode(QtGui.QPlainTextEdit.NoWrap)
        self.programEdit.setObjectName(_fromUtf8("programEdit"))
        self.verticalLayout.addWidget(self.programEdit)
        self.horizontalLayout_3 = QtGui.QHBoxLayout()
        self.horizontalLayout_3.setObjectName(_fromUtf8("horizontalLayout_3"))
        spacerItem = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem)
        self.loadButton = QtGui.QPushButton(self.centralwidget)
        self.loadButton.setObjectName(_fromUtf8("loadButton"))
        self.horizontalLayout_3.addWidget(self.loadButton)
        spacerItem1 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem1)
        self.verticalLayout.addLayout(self.horizontalLayout_3)
        self.horizontalLayout_2 = QtGui.QHBoxLayout()
        self.horizontalLayout_2.setObjectName(_fromUtf8("horizontalLayout_2"))
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        self.errorEdit = QtGui.QPlainTextEdit(self.centralwidget)
        self.errorEdit.setLineWrapMode(QtGui.QPlainTextEdit.NoWrap)
        self.errorEdit.setReadOnly(True)
        self.errorEdit.setObjectName(_fromUtf8("errorEdit"))
        self.verticalLayout.addWidget(self.errorEdit)
        self.gridLayout.addLayout(self.verticalLayout, 0, 0, 1, 1)
        self.verticalLayout_2 = QtGui.QVBoxLayout()
        self.verticalLayout_2.setObjectName(_fromUtf8("verticalLayout_2"))
        self.gridLayout.addLayout(self.verticalLayout_2, 0, 1, 1, 1)
        self.gridLayout_2.addLayout(self.gridLayout, 0, 0, 1, 1)
        BoardSimuMain.setCentralWidget(self.centralwidget)
        self.menubar = QtGui.QMenuBar(BoardSimuMain)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 546, 29))
        self.menubar.setObjectName(_fromUtf8("menubar"))
        self.menuFile = QtGui.QMenu(self.menubar)
        self.menuFile.setObjectName(_fromUtf8("menuFile"))
        self.menuBoard = QtGui.QMenu(self.menubar)
        self.menuBoard.setObjectName(_fromUtf8("menuBoard"))
        self.menuHelp = QtGui.QMenu(self.menubar)
        self.menuHelp.setObjectName(_fromUtf8("menuHelp"))
        BoardSimuMain.setMenuBar(self.menubar)
        self.statusbar = QtGui.QStatusBar(BoardSimuMain)
        self.statusbar.setObjectName(_fromUtf8("statusbar"))
        BoardSimuMain.setStatusBar(self.statusbar)
        self.actionOpen = QtGui.QAction(BoardSimuMain)
        self.actionOpen.setObjectName(_fromUtf8("actionOpen"))
        self.actionSave = QtGui.QAction(BoardSimuMain)
        self.actionSave.setObjectName(_fromUtf8("actionSave"))
        self.actionSaveAs = QtGui.QAction(BoardSimuMain)
        self.actionSaveAs.setObjectName(_fromUtf8("actionSaveAs"))
        self.actionQuit = QtGui.QAction(BoardSimuMain)
        self.actionQuit.setObjectName(_fromUtf8("actionQuit"))
        self.actionAbout = QtGui.QAction(BoardSimuMain)
        self.actionAbout.setObjectName(_fromUtf8("actionAbout"))
        self.actionNew = QtGui.QAction(BoardSimuMain)
        self.actionNew.setObjectName(_fromUtf8("actionNew"))
        self.actionAboutProcessor = QtGui.QAction(BoardSimuMain)
        self.actionAboutProcessor.setObjectName(_fromUtf8("actionAboutProcessor"))
        self.actionAboutBoard = QtGui.QAction(BoardSimuMain)
        self.actionAboutBoard.setObjectName(_fromUtf8("actionAboutBoard"))
        self.actionReleaseNotes = QtGui.QAction(BoardSimuMain)
        self.actionReleaseNotes.setObjectName(_fromUtf8("actionReleaseNotes"))
        self.menuFile.addAction(self.actionNew)
        self.menuFile.addAction(self.actionOpen)
        self.menuFile.addAction(self.actionSave)
        self.menuFile.addAction(self.actionSaveAs)
        self.menuFile.addSeparator()
        self.menuFile.addAction(self.actionQuit)
        self.menuHelp.addAction(self.actionAbout)
        self.menuHelp.addAction(self.actionReleaseNotes)
        self.menubar.addAction(self.menuFile.menuAction())
        self.menubar.addAction(self.menuBoard.menuAction())
        self.menubar.addAction(self.menuHelp.menuAction())

        self.retranslateUi(BoardSimuMain)
        QtCore.QMetaObject.connectSlotsByName(BoardSimuMain)

    def retranslateUi(self, BoardSimuMain):
        BoardSimuMain.setWindowTitle(QtGui.QApplication.translate("BoardSimuMain", "Board Simulator - Editor", None, QtGui.QApplication.UnicodeUTF8))
        self.loadButton.setText(QtGui.QApplication.translate("BoardSimuMain", "Load", None, QtGui.QApplication.UnicodeUTF8))
        self.menuFile.setTitle(QtGui.QApplication.translate("BoardSimuMain", "File", None, QtGui.QApplication.UnicodeUTF8))
        self.menuBoard.setTitle(QtGui.QApplication.translate("BoardSimuMain", "Board", None, QtGui.QApplication.UnicodeUTF8))
        self.menuHelp.setTitle(QtGui.QApplication.translate("BoardSimuMain", "Information", None, QtGui.QApplication.UnicodeUTF8))
        self.actionOpen.setText(QtGui.QApplication.translate("BoardSimuMain", "Open", None, QtGui.QApplication.UnicodeUTF8))
        self.actionSave.setText(QtGui.QApplication.translate("BoardSimuMain", "Save", None, QtGui.QApplication.UnicodeUTF8))
        self.actionSaveAs.setText(QtGui.QApplication.translate("BoardSimuMain", "Save as ...", None, QtGui.QApplication.UnicodeUTF8))
        self.actionQuit.setText(QtGui.QApplication.translate("BoardSimuMain", "Quit", None, QtGui.QApplication.UnicodeUTF8))
        self.actionAbout.setText(QtGui.QApplication.translate("BoardSimuMain", "Board Simulator", None, QtGui.QApplication.UnicodeUTF8))
        self.actionNew.setText(QtGui.QApplication.translate("BoardSimuMain", "New", None, QtGui.QApplication.UnicodeUTF8))
        self.actionAboutProcessor.setText(QtGui.QApplication.translate("BoardSimuMain", "About processor", None, QtGui.QApplication.UnicodeUTF8))
        self.actionAboutBoard.setText(QtGui.QApplication.translate("BoardSimuMain", "About board", None, QtGui.QApplication.UnicodeUTF8))
        self.actionReleaseNotes.setText(QtGui.QApplication.translate("BoardSimuMain", "Release Notes", None, QtGui.QApplication.UnicodeUTF8))

