# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '/mnt/hgfs/Developpement/Debian_Dev/Eclipse/Workspace/BoardSimu/src/Ui/boardMgrUi.ui'
#
# Created: Fri May 23 10:55:33 2014
#      by: PyQt4 UI code generator 4.9.3
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    _fromUtf8 = lambda s: s

class Ui_BoardMgr(object):
    def setupUi(self, BoardMgr):
        BoardMgr.setObjectName(_fromUtf8("BoardMgr"))
        BoardMgr.resize(761, 711)
        self.centralwidget = QtGui.QWidget(BoardMgr)
        self.centralwidget.setObjectName(_fromUtf8("centralwidget"))
        self.gridLayout = QtGui.QGridLayout(self.centralwidget)
        self.gridLayout.setObjectName(_fromUtf8("gridLayout"))
        self.hexaMode = QtGui.QRadioButton(self.centralwidget)
        self.hexaMode.setObjectName(_fromUtf8("hexaMode"))
        self.gridLayout.addWidget(self.hexaMode, 0, 0, 1, 1)
        self.globalLayout = QtGui.QGridLayout()
        self.globalLayout.setSizeConstraint(QtGui.QLayout.SetDefaultConstraint)
        self.globalLayout.setVerticalSpacing(6)
        self.globalLayout.setObjectName(_fromUtf8("globalLayout"))
        self.buttonsLayout = QtGui.QVBoxLayout()
        self.buttonsLayout.setSpacing(6)
        self.buttonsLayout.setSizeConstraint(QtGui.QLayout.SetDefaultConstraint)
        self.buttonsLayout.setObjectName(_fromUtf8("buttonsLayout"))
        self.runButton = QtGui.QPushButton(self.centralwidget)
        self.runButton.setEnabled(False)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.runButton.sizePolicy().hasHeightForWidth())
        self.runButton.setSizePolicy(sizePolicy)
        self.runButton.setObjectName(_fromUtf8("runButton"))
        self.buttonsLayout.addWidget(self.runButton)
        self.speedSlider = QtGui.QSlider(self.centralwidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Ignored, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.speedSlider.sizePolicy().hasHeightForWidth())
        self.speedSlider.setSizePolicy(sizePolicy)
        self.speedSlider.setMinimum(20)
        self.speedSlider.setMaximum(400)
        self.speedSlider.setSingleStep(20)
        self.speedSlider.setPageStep(40)
        self.speedSlider.setProperty("value", 20)
        self.speedSlider.setOrientation(QtCore.Qt.Horizontal)
        self.speedSlider.setObjectName(_fromUtf8("speedSlider"))
        self.buttonsLayout.addWidget(self.speedSlider)
        self.stopButton = QtGui.QPushButton(self.centralwidget)
        self.stopButton.setEnabled(False)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.stopButton.sizePolicy().hasHeightForWidth())
        self.stopButton.setSizePolicy(sizePolicy)
        self.stopButton.setObjectName(_fromUtf8("stopButton"))
        self.buttonsLayout.addWidget(self.stopButton)
        spacerItem = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Fixed)
        self.buttonsLayout.addItem(spacerItem)
        self.stepButton = QtGui.QPushButton(self.centralwidget)
        self.stepButton.setEnabled(False)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.stepButton.sizePolicy().hasHeightForWidth())
        self.stepButton.setSizePolicy(sizePolicy)
        self.stepButton.setObjectName(_fromUtf8("stepButton"))
        self.buttonsLayout.addWidget(self.stepButton)
        spacerItem1 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.buttonsLayout.addItem(spacerItem1)
        self.globalLayout.addLayout(self.buttonsLayout, 0, 2, 1, 1)
        self.gridLayout_2 = QtGui.QGridLayout()
        self.gridLayout_2.setObjectName(_fromUtf8("gridLayout_2"))
        self.instructionTable = QtGui.QTableWidget(self.centralwidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.instructionTable.sizePolicy().hasHeightForWidth())
        self.instructionTable.setSizePolicy(sizePolicy)
        self.instructionTable.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.instructionTable.setEditTriggers(QtGui.QAbstractItemView.NoEditTriggers)
        self.instructionTable.setShowGrid(False)
        self.instructionTable.setGridStyle(QtCore.Qt.NoPen)
        self.instructionTable.setColumnCount(3)
        self.instructionTable.setObjectName(_fromUtf8("instructionTable"))
        self.instructionTable.setRowCount(0)
        self.instructionTable.horizontalHeader().setVisible(False)
        self.instructionTable.verticalHeader().setVisible(True)
        self.gridLayout_2.addWidget(self.instructionTable, 0, 0, 1, 1)
        self.verticalLayout = QtGui.QVBoxLayout()
        self.verticalLayout.setObjectName(_fromUtf8("verticalLayout"))
        self.registerTable = QtGui.QTableWidget(self.centralwidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.registerTable.sizePolicy().hasHeightForWidth())
        self.registerTable.setSizePolicy(sizePolicy)
        self.registerTable.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.registerTable.setEditTriggers(QtGui.QAbstractItemView.NoEditTriggers)
        self.registerTable.setShowGrid(False)
        self.registerTable.setObjectName(_fromUtf8("registerTable"))
        self.registerTable.setColumnCount(0)
        self.registerTable.setRowCount(0)
        self.registerTable.horizontalHeader().setVisible(False)
        self.registerTable.horizontalHeader().setMinimumSectionSize(0)
        self.registerTable.verticalHeader().setVisible(True)
        self.verticalLayout.addWidget(self.registerTable)
        self.indicatorTable = QtGui.QTableWidget(self.centralwidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.indicatorTable.sizePolicy().hasHeightForWidth())
        self.indicatorTable.setSizePolicy(sizePolicy)
        self.indicatorTable.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.indicatorTable.setEditTriggers(QtGui.QAbstractItemView.NoEditTriggers)
        self.indicatorTable.setShowGrid(False)
        self.indicatorTable.setObjectName(_fromUtf8("indicatorTable"))
        self.indicatorTable.setColumnCount(0)
        self.indicatorTable.setRowCount(0)
        self.indicatorTable.horizontalHeader().setVisible(True)
        self.indicatorTable.horizontalHeader().setCascadingSectionResizes(True)
        self.indicatorTable.verticalHeader().setVisible(False)
        self.verticalLayout.addWidget(self.indicatorTable)
        self.gridLayout_2.addLayout(self.verticalLayout, 1, 0, 1, 1)
        self.globalLayout.addLayout(self.gridLayout_2, 0, 1, 1, 1)
        self.memoryTable = QtGui.QTableWidget(self.centralwidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.memoryTable.sizePolicy().hasHeightForWidth())
        self.memoryTable.setSizePolicy(sizePolicy)
        self.memoryTable.setMinimumSize(QtCore.QSize(300, 0))
        self.memoryTable.setAutoScroll(True)
        self.memoryTable.setEditTriggers(QtGui.QAbstractItemView.NoEditTriggers)
        self.memoryTable.setShowGrid(False)
        self.memoryTable.setObjectName(_fromUtf8("memoryTable"))
        self.memoryTable.setColumnCount(0)
        self.memoryTable.setRowCount(0)
        self.memoryTable.horizontalHeader().setVisible(False)
        self.memoryTable.verticalHeader().setVisible(True)
        self.globalLayout.addWidget(self.memoryTable, 0, 0, 1, 1)
        self.gridLayout.addLayout(self.globalLayout, 2, 0, 1, 1)
        BoardMgr.setCentralWidget(self.centralwidget)
        self.menubar = QtGui.QMenuBar(BoardMgr)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 761, 29))
        self.menubar.setObjectName(_fromUtf8("menubar"))
        self.menuHelp = QtGui.QMenu(self.menubar)
        self.menuHelp.setObjectName(_fromUtf8("menuHelp"))
        BoardMgr.setMenuBar(self.menubar)
        self.statusbar = QtGui.QStatusBar(BoardMgr)
        self.statusbar.setObjectName(_fromUtf8("statusbar"))
        BoardMgr.setStatusBar(self.statusbar)
        self.actionAboutBoard = QtGui.QAction(BoardMgr)
        self.actionAboutBoard.setObjectName(_fromUtf8("actionAboutBoard"))
        self.actionAboutProcessor = QtGui.QAction(BoardMgr)
        self.actionAboutProcessor.setObjectName(_fromUtf8("actionAboutProcessor"))
        self.menuHelp.addAction(self.actionAboutBoard)
        self.menuHelp.addAction(self.actionAboutProcessor)
        self.menubar.addAction(self.menuHelp.menuAction())

        self.retranslateUi(BoardMgr)
        QtCore.QMetaObject.connectSlotsByName(BoardMgr)

    def retranslateUi(self, BoardMgr):
        BoardMgr.setWindowTitle(QtGui.QApplication.translate("BoardMgr", "Board", None, QtGui.QApplication.UnicodeUTF8))
        self.hexaMode.setText(QtGui.QApplication.translate("BoardMgr", "Hexa", None, QtGui.QApplication.UnicodeUTF8))
        self.runButton.setText(QtGui.QApplication.translate("BoardMgr", "Run", None, QtGui.QApplication.UnicodeUTF8))
        self.stopButton.setText(QtGui.QApplication.translate("BoardMgr", "Stop", None, QtGui.QApplication.UnicodeUTF8))
        self.stepButton.setText(QtGui.QApplication.translate("BoardMgr", "Step", None, QtGui.QApplication.UnicodeUTF8))
        self.menuHelp.setTitle(QtGui.QApplication.translate("BoardMgr", "Information", None, QtGui.QApplication.UnicodeUTF8))
        self.actionAboutBoard.setText(QtGui.QApplication.translate("BoardMgr", "Board", None, QtGui.QApplication.UnicodeUTF8))
        self.actionAboutProcessor.setText(QtGui.QApplication.translate("BoardMgr", "Processor", None, QtGui.QApplication.UnicodeUTF8))

